export enum PermissionsEnum {
  ALL = 'ALL',
  CREATE_MANAGER = 'CREATE_MANAGER',
  UPDATE_MANAGER = 'UPDATE_MANAGER',
  FIND_MANAGER = 'FIND_MANAGER',
  CREATE_EXPERT = 'CREATE_EXPERT',
  UPDATE_EXPERT = 'UPDATE_EXPERT',
  FIND_EXPERT = 'FIND_EXPERT',
  CREATE_TEACHER = 'CREATE_TEACHER',
  UPDATE_TEACHER = 'UPDATE_TEACHER',
  FIND_TEACHER = 'FIND_TEACHER',
  UPLOAD_ADMISSIONS = 'UPLOAD_ADMISSIONS',
}
